name: Java CI

on: [pull_request,workflow_dispatch]
 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 13
        uses: actions/setup-java@v2
        with:
          java-version: '13'
          distribution: 'adopt'
      - name: Build with Maven
        working-directory: ./JHotDraw
        run: mvn --batch-mode --update-snapshots verify
      - name: Test with Maven
        run: mvn -B test -f ./JHotDraw/pom.xml
